import { Moment } from 'moment';

export interface IQueryCommon50SdmSuffix {
  id?: number;
  queryName?: string;
  queryDate?: Moment;
  queryUser?: string;
  col01?: string;
  col02?: string;
  col03?: string;
  col04?: string;
  col05?: string;
  col06?: string;
  col07?: string;
  col08?: string;
  col09?: string;
  col10?: string;
  col11?: string;
  col12?: string;
  col13?: string;
  col14?: string;
  col15?: string;
  col16?: string;
  col17?: string;
  col18?: string;
  col19?: string;
  col20?: string;
  col21?: string;
  col22?: string;
  col23?: string;
  col24?: string;
  col25?: string;
  col26?: string;
  col27?: string;
  col28?: string;
  col29?: string;
  col30?: string;
  col31?: string;
  col32?: string;
  col33?: string;
  col34?: string;
  col35?: string;
  col36?: string;
  col37?: string;
  col38?: string;
  col39?: string;
  col40?: string;
  col41?: string;
  col42?: string;
  col43?: string;
  col44?: string;
  col45?: string;
  col46?: string;
  col47?: string;
  col48?: string;
  col49?: string;
  col50?: string;
}

export const defaultValue: Readonly<IQueryCommon50SdmSuffix> = {};
